# Generated by Django 5.2 on 2025-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("description", models.TextField(unique=True)),
            ],
        ),
    ]
