# Generated by Django 5.2.5 on 2025-10-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
